version: '3.4'

services:
  moviesdb:
    container_name: moviesdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - movies_data:/data/db

  movies.api:
    container_name: movies.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://moviesdb:27017"
      - OMDB_API_KEY=${OMDB_API_KEY}
      - IMDB_API_KEY=${IMDB_API_KEY}
    depends_on:
      - moviesdb
    ports:
      - "8000:80"

  reservationsdb:
    container_name: reservationsdb
    restart: always
    ports:
      - "6379:6379"

  reservations.api:
    container_name: reservations.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=reservationsdb:6379"
    depends_on:
      - reservationsdb
    ports:
      - "8001:80"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=28anjavelickovic@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
        - discountdb
    ports:
      - "8003:80"

    
  administrationdb:
    container_name: administrationdb
    environment:
      - SA_PASSWORD=RS12345678
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - administrationdb_data:/var/opt/mssql/data
