version: '3.4'

services:
  moviesdb:
    image: mongo

  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Services/Movie/Movie.API/Dockerfile

  reservationsdb:
    image: redis:alpine

  reservations.api:
    image: ${DOCKER_REGISTRY-}reservations
    build:
      context: .
      dockerfile: Services/Reservations/Reservations.API/Dockerfile

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

  identitydb:
    image: mysql

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Services/Security/Identity/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
  movies_data:
  identity_data:
