version: '3.4'

services:

  moviesdb:
    image: mongo

  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Services/Movie/Movie.API/Dockerfile

  reservationsdb:
    image: redis:alpine

  reservations.api:
    image: ${DOCKER_REGISTRY-}reservations
    build:
      context: .
      dockerfile: Services/Reservations/Reservations.API/Dockerfile

volumes:
    movies_data:
