version: '3.4'

services:

  mongodb:
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  movies.api:
    container_name: movies.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
      - OMDB_API_KEY=${OMDB_API_KEY}
      - IMDB_API_KEY=${IMDB_API_KEY}
    depends_on:
      - mongodb
    ports:
      - "8000:80"

  theaterhalls.api:
    container_name: theaterhalls.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
    depends_on:
      - mongodb
    ports:
      - "8004:80"

  projections.api:
    container_name: projections.api
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
    depends_on:
       - mongodb
    ports:
       - "8005:80"

  projections.grpc:
    container_name: projections.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://mongodb:27017"
    depends_on:
       - mongodb
    ports:
       - "8006:80"

  reservationsdb:
    container_name: reservationsdb
    restart: always
    ports:
      - "6379:6379"

  reservations.api:
    container_name: reservations.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=reservationsdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc"
      - "GrpcSettings:ProjectionUrl=http://projections.grpc"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - reservationsdb
      - rabbitmq
      - discount.grpc
      - projections.grpc
    ports:
      - "8001:80"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=28anjavelickovic@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8002:80"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8003:80"

  administrationdb:
    container_name: administrationdb
    environment:
      - MSSQL_SA_PASSWORD=RSf1234_.5678
      - ACCEPT_EULA=1
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - administrationdb_data:/var/opt/mssql/data

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  administration.api:
    container_name: administration.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:AdministrationConnectionString=Server=administrationdb;Database=AdministrationDb;User Id=sa;Password=RSf1234_.5678;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on: 
      - administrationdb
      - rabbitmq
    ports:
      - "8007:80"

  identitydb:
    container_name: identitydb
    restart: always
    environment:
      - MYSQL_DATABASE=IdentityDb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - identity_data:/var/lib/mysql
 
  identity:
    container_name: identity
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:IdentityConnectionString=server=identitydb;user=user;password=1234;database=IdentityDb;
    depends_on:
      - identitydb
    ports:
      - "4000:80"