version: '3.4'

services:
  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

volumes:
  postgres_data:
  pgadmin_data: