version: '3.4'

services:
  mongodb:
    image: mongo

  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Services/Movie/Movie.API/Dockerfile

  theaterhalls.api:
    image: ${DOCKER_REGISTRY-}theaterhalls
    build:
      context: .
      dockerfile: Services/TheaterHall/TheaterHalls.API/Dockerfile

  projections.api:
    image: ${DOCKER_REGISTRY-}projections
    build:
      context: .
      dockerfile: Services/Projection/Projections.API/Dockerfile

  projections.grpc:
    image: ${DOCKER_REGISTRY-}projectionsgrpc
    build:
      context: .
      dockerfile: Services/Projection/Projections.GRPC/Dockerfile

  reservationsdb:
    image: redis:alpine

  reservations.api:
    image: ${DOCKER_REGISTRY-}reservations
    build:
      context: .
      dockerfile: Services/Reservations/Reservations.API/Dockerfile

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  administrationdb:
    platform: linux/amd64
    image: mcr.microsoft.com/azure-sql-edge

  rabbitmq:
    image: rabbitmq:3-management-alpine

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

  administration.api:
    image: ${DOCKER_REGISTRY-}administrationapi
    build:
      context: .
      dockerfile: Services/ReservationsAdministration/Administration.API/Dockerfile

  identitydb:
    platform: linux/amd64
    image: mysql

  identity:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: Services/Security/Identity/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
  movies_data:
  administrationdb_data:
  mongo_data:
  identity_data: