version: '3.4'

services:
  moviesdb:
    image: mongo

  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Services/Movie/Movie.API/Dockerfile

  reservationsdb:
    image: redis:alpine

  reservations.api:
    image: ${DOCKER_REGISTRY-}reservations
    build:
      context: .
      dockerfile: Services/Reservations/Reservations.API/Dockerfile

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  administrationdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    
  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services/Discount/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.GRPC/Dockerfile

  administration.api:
    image: ${DOCKER_REGISTRY-}administrationapi
    build:
      context: .
      dockerfile: Services/ReservationsAdministration/Administration.API/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:
  movies_data:
  administrationdb_data:
