version: '3.4'

services:

  moviesdb:
    image: mongo

  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Services/Movie/Movie.API/Dockerfile

volumes:
    movies_data: